version: 1.0
jobs:
  hello:
    steps:
      - git config --global user.email "surendhar.v+apinew1@zohotest.com"
      - git config --global user.password "Z123@crmtest"
      - git init
      - git add .
      - git commit -m "sampleFlow"
      - git branch -M testFlow
      - git remote add origin https://github.com/apinew1/erty.git
      - git push -u origin testFlow
  world:
    steps:
      - echo "World"
  hello-world:
    steps:
      - echo "Hello World!"
stages:
  - name: build
    jobs:
      - - hello
        - world
      - hello-world