version: 1.0
jobs:
  hello:
    steps:
      - git init
      - git add .
      - git push -u origin main
  world:
    steps:
      - echo "World"
  hello-world:
    steps:
      - echo "Hello World!"
stages:
  - name: build
    jobs:
      - - hello
        - world
      - hello-world